export type Question = {
  id: string;
  type: "normal" | "star";
  question: string;
  options: string[];
  answer: number;
};

export const questions: Question[] = [
  {
    id: "q1",
    type: "normal",
    question: "炊飯器がなかったので、なべでごはんを（　）。",
    options: ["にた", "むした", "たいた", "あげた"],
    answer: 2,
  },
  {
    id: "q2",
    type: "normal",
    question: "「この犬はかんだり（　）しないから、さわっても大丈夫よ。」",
    options: ["なでたり", "ほえたり", "たたいたり", "ぶったり"],
    answer: 1,
  },
  {
    id: "q3",
    type: "normal",
    question: "出かける前に、靴をきれいに（　）ましょう。",
    options: ["しぼり", "みがき", "はき", "ほし"],
    answer: 1,
  },
  {
    id: "q4",
    type: "normal",
    question: "子どもにあまりたくさんのお金を（　）いけません。",
    options: ["あたえては", "そろえては", "しあげては", "保存しては"],
    answer: 0,
  },
  {
    id: "q5",
    type: "normal",
    question: "母は私が泣くと、やさしく頭を（　）くれました。",
    options: ["こすって", "ぶって", "うなって", "なでて"],
    answer: 3,
  },
  {
    id: "q6",
    type: "normal",
    question: "「野菜を細かく（　）から、よくいためましょう。」",
    options: ["かぶせて", "くるんで", "むいて", "きざんで"],
    answer: 3,
  },
  {
    id: "q7",
    type: "normal",
    question: "この部屋は、南に大きい窓があるのでとても（　）。",
    options: ["クーラーが効いている", "日当たりがいい", "冷えている", "片づく"],
    answer: 1,
  },
  {
    id: "q8",
    type: "normal",
    question: "やせたいので、（　）が高いものは食べないようにしています。",
    options: ["バランス", "さとう", "カロリー", "味"],
    answer: 2,
  },
  {
    id: "q9",
    type: "normal",
    question: "A「あ、なべが（　）よ。」\nB「わっ、大変、忘れてた。」",
    options: ["こげてる", "かぶってる", "煮てる", "ゆでてる"],
    answer: 0,
  },
  {
    id: "q10",
    type: "normal",
    question: "（　）にほこりがたまっていると、危険です。",
    options: ["クリーニング", "コンセント", "ブラシ", "バケツ"],
    answer: 1,
  },
  {
    id: "q11",
    type: "normal",
    question: "物の上と下、あるいは、表と裏を反対にする。",
    options: ["混ぜる", "ひっくり返す", "こする", "そろえる"],
    answer: 1,
  },
  {
    id: "q12",
    type: "normal",
    question: "重さを調べる道具。",
    options: ["はかり", "カップ", "大さじ", "包丁"],
    answer: 0,
  },
  {
    id: "q13",
    type: "normal",
    question: "日に当てて乾かす。",
    options: ["ぬらす", "つるす", "たたむ", "ほす"],
    answer: 3,
  },
  {
    id: "q14",
    type: "normal",
    question: "赤ちゃんや小さいものを腕に抱く。",
    options: ["だっこする", "おんぶする", "手をつなぐ", "なでる"],
    answer: 0,
  },
  {
    id: "q15",
    type: "normal",
    question: "たくさんの熱した油の中に入れて料理する方法。",
    options: ["にる", "むす", "あげる", "ゆでる"],
    answer: 2,
  },
  {
    id: "q16",
    type: "normal",
    question: "水道の蛇口をひねる。",
    options: ["さげる", "まわす", "押す", "出す"],
    answer: 1,
  },
  {
    id: "q17",
    type: "normal",
    question: "掃除のためにいすをどける。",
    options: ["移動する", "そろえる", "置く", "かたづける"],
    answer: 0,
  },
  {
    id: "q18",
    type: "normal",
    question: "ラーメンにこしょうをふる。",
    options: ["かける", "しく", "まぜる", "ねっする"],
    answer: 0,
  },
  {
    id: "q19",
    type: "normal",
    question: "ウールのセーターが縮んだ。",
    options: ["のびた", "古くなった", "よく乾いた", "小さくなった"],
    answer: 3,
  },
  {
    id: "q20",
    type: "normal",
    question: "隣の犬はよくほえる。",
    options: ["なく", "なれる", "なでる", "おこる"],
    answer: 0,
  },
  {
    id: "q21",
    type: "normal",
    question: "敷く",
    options: ["テーブルの上にお皿を敷いてください。", "居間にソファーが敷いてあります。", "水道の蛇口を敷いて、水を出しました。", "私は畳の上に布団を敷いて寝ます。"],
    answer: 3,
  },
  {
    id: "q22",
    type: "normal",
    question: "バランス",
    options: ["バランスが効いていて、すずしいですね。", "野菜のバランスをはかりで量りましょう。", "栄養のバランスを考えて、食事を取りましょう。", "バランスの高い食品ばかり食べていると、太りますよ。"],
    answer: 2,
  },
  {
    id: "q23",
    type: "normal",
    question: "保存",
    options: ["洗濯物をたくさん保存すると、干すのが大変ですよ。", "梅雨の時期は食べ物がくさりやすいので、冷蔵庫で保存しましょう。", "ペットを保存するなら、毎日散歩に連れていきましょう。", "電子レンジで残り物を保存して食べましょう。"],
    answer: 1,
  },
  {
    id: "q24",
    type: "normal",
    question: "汚す",
    options: ["10年以上も使っているから、とても汚しています。", "雨が降ってよく汚していないから、乾燥機に入れましょう。", "きたなかったので、ぞうきんを汚して床をふきました。", "ジュースをこぼして、スカートを汚してしまいました。"],
    answer: 3,
  },
  {
    id: "q25",
    type: "normal",
    question: "わがまま",
    options: ["小さいのにわがままでえらいね！", "わがままを言って、お母さんを困らせてはいけません。", "「あれ、ドアが開かない。だれ？ わがままをしたのは！」", "「この犬はわがままだけど、みんなにしっぽを振っているよ。」"],
    answer: 1,
  },
  {
    id: "q26",
    type: "normal",
    question: "彼は小さいとき、だれとでも話をする（　）かわいい子どもでした。",
    options: ["人なつこくて", "わがままで", "いたずらで", "かわいそうで"],
    answer: 0,
  },
  {
    id: "q27",
    type: "normal",
    question: "先月、ぼくが（　）犬が死にました。",
    options: ["かわいらしかった", "かわいかった", "かわいがっていた", "かわいそうだった"],
    answer: 2,
  },
  {
    id: "q28",
    type: "normal",
    question: "ぞうきんをよく（　）から、ふいてください。",
    options: ["くんで", "はいて", "すって", "しぼって"],
    answer: 3,
  },
  {
    id: "q29",
    type: "normal",
    question: "「汚い手で目を（　）いけませんよ。」",
    options: ["こすっては", "みがいては", "そろえては", "はいては"],
    answer: 0,
  },
  {
    id: "q30",
    type: "normal",
    question: "野菜をフライパンに入れたら、よく（　）ましょう。",
    options: ["加え", "刻み", "混ぜ", "量り"],
    answer: 2,
  },
  {
    id: "q31",
    type: "normal",
    question: "材料を入れたら、（　）をして蒸してください。",
    options: ["なべ", "ふた", "おたま", "フライ返し"],
    answer: 1,
  },
  {
    id: "q32",
    type: "normal",
    question: "新しいコーヒー（　）を買いました。",
    options: ["コップ", "グラス", "ガラス", "カップ"],
    answer: 3,
  },
  {
    id: "q33",
    type: "normal",
    question: "この蛇口を（　）と、お湯が出ます。",
    options: ["しく", "あたためる", "ひねる", "いれる"],
    answer: 2,
  },
  {
    id: "q34",
    type: "normal",
    question: "旅行の（　）を調整する。",
    options: ["日帰り", "キャンセル", "日程", "休暇"],
    answer: 2,
  },
  {
    id: "q35",
    type: "normal",
    question: "A「隣のおじいさんが、（　）亡くなったんだって。」\nB「え、先週会ったとき、元気だったのに。」",
    options: ["先々週", "おととし", "さきおととい", "しあさって"],
    answer: 2,
  },
];
